# Generated by Django 4.2.4 on 2023-08-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Cientes'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='nombre'),
        ),
    ]
